[project]
name = "kea-pd-hook-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "paramiko>=4.0.0",
    "requests>=2.32.5",
    "netmiko>=4.4.0",
]
